services:
  app:
    container_name: mangaapi_server  # <--- Set a custom name here
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - nginxproxymanager_default  # <--- Ensure it belongs to the network

networks:
  nginxproxymanager_default:
    external: true
    name: nginxproxymanager_default